// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteTeste.Models;

#nullable disable

namespace SQLiteTeste.Migrations
{
    [DbContext(typeof(DogTreatmentDbContext))]
    [Migration("20231103003836_new tables")]
    partial class newtables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("SQLiteTeste.Models.FoodControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chicken")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodR")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tbFood", (string)null);
                });

            modelBuilder.Entity("SQLiteTeste.Models.WaterControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Water")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaterDrank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tbWater", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
